##ДЗ МОДУЛЯ 9##

In [1]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
from math import comb

In [2]:
### Уровень 1 
import pandas as pd
df = pd.read_csv('C:\\Users\\User\\Documents\\ДЗ\\train.csv') 
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [3]:
df['Age'].fillna(df.groupby(['Pclass', 'Sex'])['Age'].transform('median'))

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    21.5
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [4]:
pa=(df['Survived']==1).mean()## pa - вероятность выживания
pa

np.float64(0.3838383838383838)

In [5]:
man=(df[df['Sex']=='male']['Survived']).mean()## вероятность выживания мужчин.
man

np.float64(0.18890814558058924)

In [6]:
fem=(df[df['Sex']=='female']['Survived']).mean()##  - вероятность выживания  женщины
fem

np.float64(0.7420382165605095)

In [7]:
sur1=(df[df['Pclass'] == 1]['Survived']).mean() ## вероятноость выживания 1-ого класса
sur1

np.float64(0.6296296296296297)

In [8]:
n=len(df)
n1=(df['Sex']=='female').sum() ## число выборки женщин
n2=(df['Pclass']==1).sum() ## число выборки 1-ого класса
n3=(df['Sex']=='male').sum()## число выборки мужчин

In [9]:
def interval(p,n):## p - вероятность выживания(т.к распределение Бернулли то оно же и будет матожиданием p=M)
    q=1-p ## q - вероятность невыживания
    sigma=(p*(1-p))**0.5 ## sigma - стандартное отклонение в выборке
    sd =sigma/(n)**0.5## sd - стандартная ошибка
    return st.norm.interval(0.95,p,sd)
res1 = interval(pa,n)
res2  = interval(fem,n1)
res3  = interval(sur1,n2)
print(res1)
print(res2)
print(res3)
## res 1 - безусловная вероятность ,res2,res 3 -условные. res 1 не перекрывается с res 2  =>их средние в генеральной совокупности не равны ,значит выжиавемость завистит от пола ( с вероятностью ошибки 1-ого рода 5%)
## Отсюда же можно сделать вывод, что наиболее критична тут ошибка 1-ого рода т.к мы оцениваем влияние двух факторов. Остальные факторы ( возможно упущенные по ошибке 2-ого рода нас тут не интересуют)
## res 1  и res 3 не  перекрываются, значит мы  можем по даанным интервалам сделать вывод о влиянии класса на выживаемость

(np.float64(0.3519060427032577), np.float64(0.4157707249735099))
(np.float64(0.693646158912385), np.float64(0.790430274208634))
(np.float64(0.5652302161570761), np.float64(0.6940290431021832))

## res 1 - безусловная вероятность ,res2,res 3 -условные. res 1 не перекрывается с res 2  =>их средние в генеральной совокупности не равны ,значит выжиавемость завистит от пола ( с вероятностью ошибки 1-ого рода 5%)
## Отсюда же можно сделать вывод, что наиболее критична тут ошибка 1-ого рода т.к мы оцениваем влияние двух факторов. Остальные факторы ( возможно упущенные по ошибке 2-ого рода нас тут не интересуют)
## res 1  и res 3 не  перекрываются, значит мы  можем по даанным интервалам сделать вывод о влиянии класса на выживаемость

In [10]:
u1=st.t.interval(0.95, df=n-1, loc=np.mean(df['Survived']), scale=st.sem(df['Survived']))##выбранный уровнем достоверности 0.95
u2=st.t.interval(0.95, df=n-1, loc=np.mean(df[df['Sex']=='female']['Survived']), scale=st.sem(df[df['Sex']=='female']['Survived']))
u3=st.t.interval(0.95, df=n-1, loc=np.mean(df[df['Pclass'] == 1]['Survived']), scale=st.sem(df[df['Pclass'] == 1]['Survived']))
print(u1)
print(u2)
print(u3)

(np.float64(0.3518445989680297), np.float64(0.4158321687087379))
(np.float64(0.6935029124169697), np.float64(0.7905735207040493))
(np.float64(0.5649927222611922), np.float64(0.6942665369980671))

## Результаты сошлись с точнстью (10**-3)

In [11]:
from scipy.stats import norm ## p - доверительный интервал через функцию указанную в лекции на примере общего чила паасажиров
alpha = 0.05 
q=1-pa
sigma=(pa*q)**0.5
sd =sigma/(n)**0.5
def get_confidence_interval(pa, sigma, n, alpha):
    h = norm.ppf(1 - alpha / 2) * sigma / np.sqrt(n)
    return pa - h, pa + h

confidence_interval = get_confidence_interval(pa, sigma, n, alpha)

confidence_interval

(np.float64(0.3519060427032577), np.float64(0.4157707249735099))

## Уровень 2

In [12]:
## Исходные данные
##X1= fem  вероятность выживания женщин.
##X2= man  вероятность выживания мужчин.
from scipy.stats import t
def t_test(X1,X2,n1,n2):
    q1=1-X1## вероятность невыживания женщин.
    q2=1-X2## вероятность невыживания мужчин.
    sigma1=(X1*q1)**0.5
    sigma2=(X2*q2)**0.5
    se=(((sigma1**2)/n1)+((sigma2**2)/n2))**0.5
    ## Допускаем Гипотзу H0 - в генеральной совокупности средние М1 =М2 - т.е выживаемость не зависит от пола
    t_score= (X1-X2)/(se)##t -критерий 
    df=n1+n3-2 ##df -число степеней свободы
    p_value = 2 * (1 - t.cdf(np.abs(t_score), df))
    if p_value < alpha:
        return( "Можно отвергнуть нулевую гипотезу.Выживаемость зависит от пола")
    else:
        return("Нулевую гипотезу отвергнуть нельзя")
T1 = t_test(fem,man,n1,n3)
T1

'Можно отвергнуть нулевую гипотезу.Выживаемость зависит от пола'

In [13]:
chld=df[df['Age'] <=18]['Survived'].mean()
adlt=df[df['Age'] >18]['Survived'].mean()
n4=(df['Age'] <=18).sum()
n5=(df['Age'] >18).sum()

In [14]:
T2 = t_test(chld,adlt,n4,n5)
T2

'Можно отвергнуть нулевую гипотезу.Выживаемость зависит от пола'

## Через X-квадрат χ² = Σ (O − E)² / E где O — наблюдаемые частоты, E — ожидаемые при H0
## Нулевая гипотеза H0: выживаемость не зависит от пола

In [15]:
table=pd.crosstab(df['Sex'],df['Survived'])
table

Survived    0    1
Sex
female     81  233
male      468  109

In [16]:
chi, p, dof, expected= st.chi2_contingency(table)
print("chi =", chi)
print("p =", p)
print("df =", dof) ##df = (2−1)*(2−1) = 1
print("expected frequencies:\n", expected)

chi = 260.71702016732104
p = 1.1973570627755645e-58
df = 1
expected frequencies:
 [[193.47474747 120.52525253]
 [355.52525253 221.47474747]]

In [17]:
if p < alpha:
    print( "Можно отвергнуть нулевую гипотезу.Выживаемость зависит от пола с уровнем достоверности 0.95 ")
else:
    print("Нулевую гипотезу отвергнуть нельзя.Нужны доп.исследования")

Можно отвергнуть нулевую гипотезу.Выживаемость зависит от пола с уровнем достоверности 0.95

## теперь проверяем детей и взрослых
## Нулевая гипотеза H0: выживаемость не зависит от возраста

In [18]:
O5=(df[df['Survived'] == 1]['Age'] <=18).sum() ## детей выжило 
O6=(df[df['Survived'] == 0]['Age'] <=18).sum()## детей не выжило
O7=(df[df['Survived'] == 1]['Age'] >18).sum()## взрослых  выжило
O8=(df[df['Survived'] == 0]['Age'] >18).sum()## взрослых не выжило

In [19]:
table2 = np.array([[O5, O6],
                  [O7, O8]])
table2

array([[ 70,  69],
       [220, 355]])

In [20]:
chi2, p2, dof2, expected2= st.chi2_contingency(table2)
print("chi =", chi2)
print("p =", p2)
print("df =", dof2) ##df = (2−1)*(2−1) = 1
print("expected frequencies:\n", expected2)

chi = 6.301311052021158
p = 0.012064871031697809
df = 1
expected frequencies:
 [[ 56.45658263  82.54341737]
 [233.54341737 341.45658263]]

In [21]:
if p2 < alpha:
    print( "Можно отвергнуть нулевую гипотезу.Выживаемость зависит от возраста с уровнем достоверности 0.95")
else:
    print("Нулевую гипотезу отвергнуть нельзя.Нужны доп.исследования")

Можно отвергнуть нулевую гипотезу.Выживаемость зависит от возраста с уровнем достоверности 0.95

In [22]:
## Уровень 3

In [23]:
## Исходные данные
alpha=0.01
m=10000
p=0.5
n=10
binom1=np.random.binomial(n,p,m)

In [24]:
binom1

array([5, 3, 5, ..., 2, 6, 4], shape=(10000,), dtype=int32)

In [27]:
## Считаем вероятность для биноминального распределения
## Определяем p-value 
# для поимки экстрасенса нам нужно отсечь вероятности слева от матожидания k=5
# p-values для всех участников (правосторонние)
pvals_right = np.array([1 - st.binom.cdf(k - 1, n, p) for k in binom1])
# без корректировки: считаем, кто попал по α=0.01
res1 = (pvals_right <= alpha).sum()
res1
# Вводим поправку Бонферрони
alpha_k = alpha / m
res2 = (pvals_right <= alpha_k).sum()
print("Количество обнаруженных без коррекции (α=0.01):", res1)
print("Количество обнаруженных с поправкой Бонферрони:", res2)

Количество обнаруженных без коррекции (α=0.01): 11
Количество обнаруженных с поправкой Бонферрони: 0