In [209]:
##ДЗ МОДУЛЯ 9##

In [210]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
from math import comb

In [211]:
### Уровень 1 
import pandas as pd
df = pd.read_csv('C:\\Users\\User\\Documents\\ДЗ\\train.csv') 
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [212]:
df['Age'].fillna(df.groupby(['Pclass', 'Sex'])['Age'].transform('median'))

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    21.5
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [213]:
pa=(df['Survived']==1).mean()## pa - вероятность выживания
pa

np.float64(0.3838383838383838)

In [214]:
man=(df[df['Survived'] == 1]['Sex']=='male').mean()## вероятность выживания мужчин.
man

np.float64(0.31871345029239767)

In [215]:
fem=(df[df['Survived'] == 1]['Sex']=='female').mean()##  - вероятность выживания  женщины
fem

np.float64(0.6812865497076024)

In [216]:
sur1=(df[df['Survived'] == 1]['Pclass'] == 1).mean() ## вероятноость выживания 1-ого класса
sur1

np.float64(0.39766081871345027)

In [217]:
sur2=(df[df['Survived'] == 1]['Pclass'] == 2).mean() ## вероятноость выживания  2-ого класса

In [218]:
sur3=(df[df['Survived'] == 1]['Pclass'] == 3).mean() ## пвероятноость выживания  3-ого класса
sur3

np.float64(0.347953216374269)

In [219]:
n=len(df)
n1=(df['Sex']=='female').sum() ## число выборки женщин
n2=(df['Pclass']==1).sum() ## число выборки 1-ого класса
n3=(df['Sex']=='male').sum()## число выборки мужчин

In [223]:
def interval(p,n):## p - вероятность выживания(т.к распределение Бернулли то оно же и будет матожиданием p=M)
    q=1-p ## q - вероятность невыживания
    sigma=(p*(1-p))**0.5 ## sigma - стандартное отклонение в выборке
    sd =sigma/(n)**0.5## sd - стандартная ошибка
    return st.norm.interval(0.95,p,sd)
res1 = interval(pa,n)
res2  = interval(fem,n1)
res3  = interval(sur1,n2)
print(res1)
print(res2)
print(res3)
## res 1 - безусловная вероятность ,res2,res 3 -условные. res 1 не перекрывается с res 2  =>их средние в генеральной совокупности не равны ,значит выжиавемость завистит от пола ( с вероятностью ошибки 1-ого рода 5%)
## Отсюда же можно сделать вывод, что наиболее критична тут ошибка 1-ого рода т.к мы оцениваем влияние двух факторов. Остальные факторы ( возможно упущенные по ошибке 2-ого рода нас тут не интересуют)
## res 1  и res 3 перекрываются, значит мы не можем по даанным интервалам сделать вывод о влиянии класса на выживаемость

(np.float64(0.3519060427032577), np.float64(0.4157707249735099))
(np.float64(0.6297460802029915), np.float64(0.7328270192122133))
(np.float64(0.33239313898597944), np.float64(0.4629284984409211))

In [180]:
u=st.t.interval(0.95, df=n-1, loc=np.mean(pa), scale=st.sem(pa))##выбранный уровнем достоверности 0.95
u

C:\Users\User\AppData\Local\Temp\ipykernel_28992\2915678322.py:1: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  u=st.t.interval(0.95, df=n-1, loc=np.mean(pa), scale=st.sem(pa))

(np.float64(nan), np.float64(nan))

In [225]:
u1=st.t.interval(0.95, df=n-1, loc=np.mean(pa), scale=sd)
u1

(np.float64(0.3518625578719821), np.float64(0.4158142098047855))

In [181]:
from scipy.stats import norm ## p - доверительный интервал через функцию указанную в лекции на примере общего чила паасажиров
alpha = 0.05 
q=1-pa
sigma=(pa*q)**0.5
sd =sigma/(n)**0.5
def get_confidence_interval(pa, sigma, n, alpha):
    h = norm.ppf(1 - alpha / 2) * sigma / np.sqrt(n)
    return pa - h, pa + h

confidence_interval = get_confidence_interval(pa, sigma, n, alpha)

confidence_interval

(np.float64(0.3519060427032577), np.float64(0.4157707249735099))

In [182]:
## Уровень 2

In [183]:
## Исходные данные
##X1= fem  вероятность выживания женщин.
##X2= man  вероятность выживания мужчин.
from scipy.stats import t
def t_test(X1,X2,n1,n2):
    q1=1-X1## вероятность невыживания женщин.
    q2=1-X2## вероятность невыживания мужчин.
    sigma1=(X1*q1)**0.5
    sigma2=(X2*q2)**0.5
    se=(((sigma1**2)/n1)+((sigma2**2)/n2))**0.5
    ## Допускаем Гипотзу H0 - в генеральной совокупности средние М1 =М2 - т.е выживаемость не зависит от пола
    t_score= (X1-X2)/(se)##t -критерий 
    df=n1+n3-2 ##df -число степеней свободы
    p_value = 2 * (1 - t.cdf(np.abs(t_score), df))
    if p_value < alpha:
        return( "Можно отвергнуть нулевую гипотезу.Выживаемость зависит от пола")
    else:
        return("Нулевую гипотезу отвергнуть нельзя")
T1 = t_test(fem,man,n1,n3)
T1

'Можно отвергнуть нулевую гипотезу'

In [184]:
chld=df[df['Age'] <=18]['Survived'].mean()
adlt=df[df['Age'] >18]['Survived'].mean()
n4=(df['Age'] <=18).sum()
n5=(df['Age'] >18).sum()

In [185]:
T2 = t_test(chld,adlt,n4,n5)
T2

'Можно отвергнуть нулевую гипотезу'

In [186]:
## Через X-квадрат χ² = Σ (O − E)² / E где O — наблюдаемые частоты, E — ожидаемые при H0
## Нулевая гипотеза H0: выживаемость не зависит от пола

In [187]:
table=pd.crosstab(df['Sex'],df['Survived'])
table

Survived    0    1
Sex
female     81  233
male      468  109

In [188]:
chi, p, dof, expected= st.chi2_contingency(table)
print("chi =", chi)
print("p =", p)
print("df =", dof) ##df = (2−1)*(2−1) = 1
print("expected frequencies:\n", expected)

chi = 260.71702016732104
p = 1.1973570627755645e-58
df = 1
expected frequencies:
 [[193.47474747 120.52525253]
 [355.52525253 221.47474747]]

In [189]:
if p < alpha:
    print( "Можно отвергнуть нулевую гипотезу.Выживаемость зависит от пола с уровнем достоверности 0.95 ")
else:
    print("Нулевую гипотезу отвергнуть нельзя.Нужны доп.исследования")

Можно отвергнуть нулевую гипотезу.Выживаемость зависит от пола

In [190]:
## теперь проверяем детей и взрослых
## Нулевая гипотеза H0: выживаемость не зависит от возраста

In [191]:
O5=(df[df['Survived'] == 1]['Age'] <=18).sum() ## детей выжило 
O6=(df[df['Survived'] == 0]['Age'] <=18).sum()## детей не выжило
O7=(df[df['Survived'] == 1]['Age'] >18).sum()## взрослых  выжило
O8=(df[df['Survived'] == 0]['Age'] >18).sum()## взрослых не выжило

In [192]:
table2 = np.array([[O5, O6],
                  [O7, O8]])
table2

array([[ 70,  69],
       [220, 355]])

In [193]:
chi2, p2, dof2, expected2= st.chi2_contingency(table2)
print("chi =", chi2)
print("p =", p2)
print("df =", dof2) ##df = (2−1)*(2−1) = 1
print("expected frequencies:\n", expected2)

chi = 6.301311052021158
p = 0.012064871031697809
df = 1
expected frequencies:
 [[ 56.45658263  82.54341737]
 [233.54341737 341.45658263]]

In [194]:
if p2 < alpha:
    print( "Можно отвергнуть нулевую гипотезу.Выживаемость зависит от возраста с уровнем достоверности 0.95")
else:
    print("Нулевую гипотезу отвергнуть нельзя.Нужны доп.исследования")

Можно отвергнуть нулевую гипотезу.Выживаемость зависит от возраста

In [195]:
## Уровень 3

In [205]:
## Исходные данные
alpha=0.01
m=1000
p=0.5
n=10
binom1=np.random.binomial(n,p,m)

In [206]:
binom1

array([ 3,  2,  4,  6,  6,  6,  6,  5,  5,  4,  5,  6,  3,  5,  3,  5,  3,
        3,  3,  7,  5,  4,  3,  5,  3,  6,  5,  6,  5,  6,  6,  5,  7,  5,
        5,  4,  7,  5,  5,  5,  3,  4,  4,  5,  6,  4,  3,  5,  7,  5,  5,
        4,  6,  3,  3, 10,  6,  5,  6,  9,  4,  6,  4,  6,  6,  9,  3,  1,
        6,  5,  6,  6,  5,  4,  6,  5,  5,  7,  3,  1,  4,  6,  5,  8,  5,
        4,  6,  6,  6,  6,  5,  4,  3,  4,  2,  5,  4,  6,  4,  3,  7,  3,
        6,  7,  3,  5,  5,  6,  6,  4,  1,  5,  7,  7,  3,  7,  2,  3,  8,
        5,  3,  5,  2,  2,  5,  4,  5,  4,  3,  8,  4,  3,  4,  4,  4,  4,
        6,  3,  4,  3,  8,  3,  5,  5,  6,  4,  6,  2,  7,  3,  5,  4,  4,
        6,  3,  4,  6,  7,  5,  5,  3,  3,  8,  1,  5,  6,  4,  5,  5,  4,
        7,  7,  6,  1,  6,  4,  4,  4,  5,  5,  4,  7,  4,  6,  2,  4,  6,
        5,  6,  5,  5,  3,  3,  7,  5,  5,  6,  2,  5,  7,  5,  5,  5,  7,
        5,  6,  6,  2,  8,  6,  5,  2,  7,  5,  7,  5,  5,  7,  5,  4,  5,
        5,  6,  7,  2,  5,  4,  3,  6,  7,  5,  4,  6,  5,  6,  8,  5,  4,
        4,  6,  8,  4,  5,  5,  8,  4,  8,  5,  6,  6,  3,  8,  8,  7,  7,
        4,  7,  7,  4,  3,  6,  5,  3,  5,  4,  6,  5,  6,  6,  6,  5,  7,
        4,  5,  6,  4,  4,  6,  6,  7,  5,  6,  3,  4,  6,  3,  8,  3,  6,
        4,  6,  5,  6,  7,  5,  3,  8,  5,  4,  5,  6,  7,  7,  3,  7,  5,
        5,  5,  6,  7,  6,  3,  6,  2,  5,  5,  5,  4,  5,  6,  4,  6,  2,
        3,  7,  5,  2,  5,  5,  3,  4,  5,  6,  7,  5,  3,  3,  5,  4,  7,
        4,  4,  5,  4,  6,  5,  7,  7,  5,  5,  5,  6,  4,  4,  5,  4,  5,
        1,  6,  3,  6,  4,  3,  5,  8,  5,  7,  3,  5,  6,  4,  3,  2,  5,
        6,  9,  5,  4,  4,  3,  5,  6,  6,  2,  6,  6,  5,  7,  4,  7,  4,
        4,  4,  7,  6,  5,  5,  2,  6,  8,  6,  4,  4,  5,  5,  4,  6,  6,
        6,  1,  7,  4,  2,  6,  6,  6,  5,  7,  4,  5,  7,  6,  3,  6,  7,
        6,  5,  6,  3,  4,  7,  2,  5,  7,  5,  3,  5,  6,  4,  7,  7,  3,
        3,  4,  5,  3,  4,  7,  6,  5,  6,  1,  3,  6,  6,  7,  5,  5,  5,
        6,  7,  5,  4,  2,  6,  6,  5,  5,  7,  7,  4,  7,  5,  3,  4,  6,
        7,  3,  5,  6,  4,  6,  3,  4,  0,  5,  4,  3,  7,  4,  5,  4,  5,
        6,  6,  4,  2,  7,  8,  7,  3,  6,  5,  6,  5,  5,  6,  5,  5,  3,
        7,  6,  8,  6,  5,  7,  6,  4,  4,  5,  6,  6,  4,  7,  5,  6,  6,
        7,  4,  5,  7,  7,  5,  5,  6,  3,  4,  4,  5,  6,  3,  8,  5,  6,
        4,  5,  8,  6,  2,  4,  4,  8,  6,  6,  3,  6,  4,  3,  7,  1,  3,
        7,  4,  6,  6,  3,  6,  4,  6,  5,  5,  8,  4,  4,  4,  4,  5,  6,
        7,  3,  6,  5,  5,  6,  7,  6,  3,  8,  7,  4,  3,  6,  8,  3,  6,
        1,  2,  6,  6,  4,  5,  6,  7,  4,  6,  4,  5,  6,  6,  5,  6,  2,
        4,  4,  3,  4,  7,  7,  5,  5,  5,  8,  7,  4,  3,  2,  4,  5,  4,
        7,  7,  6,  5,  7,  7,  7,  4,  7,  4,  3,  6,  6,  8,  5,  4,  3,
        5,  5,  5,  3,  4,  7,  5,  5,  5,  5,  3,  4,  5,  5,  5,  4,  6,
        6,  8,  2,  6,  3,  4,  7,  6,  6,  5,  2,  4,  5,  5,  5,  2,  6,
        5,  2,  7,  4,  3,  6,  4,  5,  1,  5,  2,  4,  4,  8,  4,  7,  5,
        7,  6,  1,  3,  2,  3,  4,  6,  6,  4,  5,  7,  3,  5,  3,  9,  5,
        7,  3,  9,  3,  3,  6,  6,  4,  4,  5,  7,  6,  7,  7,  3,  5,  8,
        3,  5,  6,  9,  3,  5,  6,  5,  7,  3,  5,  5,  6,  7,  5,  5,  1,
        6,  2,  6,  5,  8,  3,  5,  7,  5,  6,  5,  6,  7,  3,  7,  4,  6,
        5,  4,  8,  7,  4,  4,  4,  4,  3,  7,  7,  7,  5,  6,  4,  7,  7,
        5,  5,  5,  4,  3,  5,  6,  6,  7,  5,  3,  5,  2,  5,  4,  7,  3,
        5,  5,  7,  5,  5,  5,  4,  5,  4,  3,  6,  4,  4,  0,  2,  4,  4,
        6,  4,  6,  5,  4,  3,  1,  5,  5,  4,  6,  3,  3,  4,  5,  6,  7,
        4,  3,  5,  4,  8,  2,  4,  6,  5,  5,  6,  6,  5,  6,  3,  3,  5,
        4,  9,  6,  7,  4,  6,  2,  6,  2,  6,  4,  5,  4,  2,  6,  5,  6,
        3,  5,  2,  3,  6,  4,  3,  3,  3,  7,  5,  6,  4,  6,  7,  5,  7,
        4,  8,  3,  6,  4,  3,  5,  4,  4,  5,  8,  6,  4,  8,  4,  6,  4,
        6,  6,  5,  5,  4,  5,  7,  2,  6,  7,  5,  4,  4,  6,  4,  1,  3,
        4,  5,  4,  6,  4,  5,  6,  6,  4,  4,  3,  3,  5,  4,  5,  5,  5,
        7,  4,  7,  2,  2,  3,  6,  5,  3,  3,  5,  8,  4,  4,  3,  5,  7,
        4,  5,  7,  6,  5,  6,  6,  6,  5,  4,  4,  7,  3,  4,  6,  5,  5,
        3,  3,  6,  5,  4,  4,  5,  6,  5,  3,  3,  3,  2,  6,  7,  5,  8,
        7,  7,  4,  8,  6,  4,  7,  1,  5,  5,  3,  7,  4,  4],
      dtype=int32)

In [207]:
## Считаем вероятность для биноминального распределения
## Определяем p-value 
def binom_right_pvalue(k, n, p):
    # для поимки экстрасенса нам нужно отсечь вероятности слева от матожидания k=5
    return sum(st.binom.pmf(i, n, p) for i in range(k, n+1))
# p-values для всех участников (правосторонние)
pvals_right = np.array([binom_right_pvalue(k, n, p) for k in binom1])
# без корректировки: считаем, кто попал по α=0.01
res1 = (pvals_right <= alpha).sum()
res1
# Вводим поправку Бонферрони
alpha_k = alpha / m
res2 = (pvals_right <= alpha_k).sum()
print("Количество обнаруженных без коррекции (α=0.01):", res1)
print("Количество обнаруженных с поправкой Бонферрони:", res2)

Количество обнаруженных без коррекции (α=0.01): 1
Количество обнаруженных с поправкой Бонферрони: 0