In [68]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression, SGDRegressor, SGDClassifier, Ridge, Lasso

In [69]:
df = pd.read_csv('C:\\Users\\User\\Documents\\ДЗ\\train.csv') 
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [70]:
df['Age'].fillna(df.groupby(['Pclass', 'Sex'])['Age'].transform('median'))

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    21.5
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [71]:
df = df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin', 'Embarked'], axis=1)

In [72]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare
0           0       3    male  22.0      1      0   7.2500
1           1       1  female  38.0      1      0  71.2833
2           1       3  female  26.0      0      0   7.9250
3           1       1  female  35.0      1      0  53.1000
4           0       3    male  35.0      0      0   8.0500
..        ...     ...     ...   ...    ...    ...      ...
886         0       2    male  27.0      0      0  13.0000
887         1       1  female  19.0      0      0  30.0000
888         0       3  female   NaN      1      2  23.4500
889         1       1    male  26.0      0      0  30.0000
890         0       3    male  32.0      0      0   7.7500

[891 rows x 7 columns]

In [73]:
df['Sex'] = (df['Sex'] == 'male').astype('int')
df

     Survived  Pclass  Sex   Age  SibSp  Parch     Fare
0           0       3    1  22.0      1      0   7.2500
1           1       1    0  38.0      1      0  71.2833
2           1       3    0  26.0      0      0   7.9250
3           1       1    0  35.0      1      0  53.1000
4           0       3    1  35.0      0      0   8.0500
..        ...     ...  ...   ...    ...    ...      ...
886         0       2    1  27.0      0      0  13.0000
887         1       1    0  19.0      0      0  30.0000
888         0       3    0   NaN      1      2  23.4500
889         1       1    1  26.0      0      0  30.0000
890         0       3    1  32.0      0      0   7.7500

[891 rows x 7 columns]

In [74]:
df.dropna(axis=0, how="any", inplace=True)

In [75]:
X=np.array(df[['Pclass','Sex','Age']]) ## Создаем маасив X - матрицу с признаками: пол, возраст, класс
X

array([[ 3.,  1., 22.],
       [ 1.,  0., 38.],
       [ 3.,  0., 26.],
       ...,
       [ 1.,  0., 19.],
       [ 1.,  1., 26.],
       [ 3.,  1., 32.]], shape=(714, 3))

In [76]:
y=np.array(df[['Survived']]) ## y - известный параметр выживания

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,shuffle=True)

In [78]:
model=LogisticRegression() ## Обучаем логистическую  модель 
model.fit(X_train,y_train)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [79]:
model_1=LinearRegression() ## Обучаем линейную  модель 
model_1.fit(X_train,y_train)

LinearRegression()

In [80]:
model.coef_,model.intercept_ ## находим веса модели (wo-w3)

(array([[-1.24867576, -2.53214184, -0.04253273]]), array([5.16996237]))

In [81]:
y_pred=model.predict(X_test) ## предсказание по тестовой выборке
y_pred

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [82]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [88]:
df=pd.DataFrame(X_test) ## Таблица результатов через фунцию LogisticRegression()
df['y_test']=y_test
df['y_pred']=y_pred
df.head()

     0    1     2  y_test  y_pred
0  2.0  1.0  42.0       0       0
1  2.0  1.0   3.0       1       1
2  2.0  0.0  29.0       1       1
3  1.0  0.0  24.0       1       1
4  3.0  1.0  43.0       0       0

In [90]:
df1=pd.DataFrame(X_test) ## Таблица результатов через фунцию LinearRegression()
df1['y']=y_test
## показатели линейной модели df['pred_linear']=model_1.predict(X) 
df1['sigm']=sigmoid(model_1.predict(X_test)) ## показатели линейной модели прогоняем через сигмоиду
df1.head() ## Итоговый вывод датасета

     0    1     2  y      sigm
0  2.0  1.0  42.0  0  0.548682
1  2.0  1.0   3.0  1  0.608223
2  2.0  0.0  29.0  1  0.685954
3  1.0  0.0  24.0  1  0.732693
4  3.0  1.0  43.0  0  0.498342

In [91]:
accuracy_score(y_test, y_pred,normalize=True)  ##Точность логистической регрессии

0.7482517482517482

In [95]:
accuracy_score(df1['y'], df1['sigm'] > 0.7) ##Точность линейной регрессии+ сигмоида с порогом классификации 0,7

0.6993006993006993

In [96]:
model.score(X_test,y_test) ##Точность логистической регрессии

0.7482517482517482

In [25]:
## Уровень 2

In [28]:
from sklearn.datasets import load_boston
data = load_boston()

ImportError:
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>

In [27]:
x_df = pd.DataFrame(data['data'], columns=data['feature_names'])
y_df = pd.DataFrame(data['target'], columns=['y'])

NameError: name 'data' is not defined